export default {
    path:"/classify",
    component: () => import("../views/classify.vue"),
    children:[
        {
            path:"classify/tushu",
            redirect:"tushu"
        },
        {
            path:"tushu",
            component:()=>import("../components/classify/tushu.vue")
        },
        {
            path:"tongshu",
            component:()=>import("../components/classify/tongshu.vue")
        },
        {
            path:"jiushu",
            component:()=>import("../components/classify/jiushu.vue")
        },
        {
            path:"nv",
            component:()=>import("../components/classify/nv.vue")
        },
        {
            path:"shouji",
            component:()=>import("../components/classify/shouji.vue")
        },
        {
            path:"dianzishu",
            component:()=>import("../components/classify/dianzishu.vue")
        },
        {
            path:"wenju",
            component:()=>import("../components/classify/wenju.vue")
        },
        {
            path:"banggong",
            component:()=>import("../components/classify/banggong.vue")
        },
        {
            path:"shiping",
            component:()=>import("../components/classify/shiping.vue")
        },
        {
            path:"muying",
            component:()=>import("../components/classify/muying.vue")
        },
        {
            path:"tongxie",
            component:()=>import("../components/classify/tongxie.vue")
        },
        {
            path:"yundong",
            component:()=>import("../components/classify/yundong.vue")
        },
    ],
    // linkActiveClass:"con"
};